[project]
name = "ecg5000-project"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "black>=26.5.1",
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
    "scikit-learn>=1.6.1",
    "scipy>=1.13.1",
    "seaborn>=0.13.2",
    "snntorch>=0.9.4",
    "torch>=2.8.0",
    "torchaudio>=2.11.0",
    "torchvision>=0.23.0",
    "tqdm>=4.67.3",
]
